
export const CREATE_BlOG = 'CREATE_BlOG';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const FETCH_SSE_NOTIFICATION = 'FETCH_SSE_NOTIFICATION';

// Portfolio
export const PORTFOLIO_LIST_START = 'PORTFOLIO_LIST_START';
export const PORTFOLIO_LIST_SUCCESS = 'PORTFOLIO_LIST_SUCCESS';
export const PORTFOLIO_LIST_FAIL = 'PORTFOLIO_LIST_FAIL';

//Blogs
export const UPDATE_CHART_LIST = 'UPDATE_CHART_LIST';

//Company
export const SET_COMPANY_INFO = 'SET_COMPANY_INFO';

// Daaf : Dynamic Asset Allocation

export const FETCH_DAAF_DATA_START = 'FETCH_DAAF_DATA_START';
export const FETCH_DAAF_DATA_SUCCESS = 'FETCH_DAAF_DATA_SUCCESS';
export const FETCH_DAAF_DATA_FAIL = 'FETCH_DAAF_DATA_FAIL';

export const FETCH_ASSET_START = 'FETCH_ASSET_START';
export const FETCH_ASSET_SUCCESS = 'FETCH_ASSET_SUCCESS';
export const FETCH_ASSET_FAIL = 'FETCH_ASSET_FAIL';